name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Testar código
        run: npm test

      - name: Construir imagem Docker
        run: docker build -t automation-service ./automation-service

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Autenticar no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Enviar imagem ao Docker Hub
        run: docker tag automation-service myrepo/automation-service:latest && docker push myrepo/automation-service:latest

      - name: Enviar imagem ao AWS ECR (opcional)
        run: aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URL }}

      - name: Fazer deploy no Kubernetes
        run: kubectl apply -f k8s/deployment.yaml